project:
  type: website
  resources:
    - CNAME

website:
  title: "Patrick E. Shea"
  description: "Senior Lecturer in International Political Economy & Development, University of Glasgow"
  site-url: "https://patrickshea.co.uk"
  repo-url: "https://github.com/patrickeshea/patrickshea-site"
  
  navbar:
    pinned: true
    left:
      - text: "About"
        href: index.qmd
      - text: "Research"
        menu:
          - text: "Overview"
            href: research/index.qmd
          - text: "Book"
            href: research/book/index.qmd
          - text: "Articles"
            href: research/articles/index.qmd
          - text: "Working Papers"
            href: research/working-papers/index.qmd
      - text: "Teaching"
        href: teaching/index.qmd
      - text: "Commentary"
        href: commentary/index.qmd
      - text: "CV"
        href: cv/index.qmd
    right:
      - icon: envelope
        href: "mailto:patrick.shea@glasgow.ac.uk"
      - icon: github
        href: https://github.com/patrickeshea
      - icon: google
        href: "https://scholar.google.com/citations?user=1tPGawwAAAAJ&hl=en"
      - icon: linkedin
        href: "https://www.linkedin.com/in/patrick-shea-7bb956330/"

  page-footer:
    left: "© 2026 Patrick E. Shea"
    right: "Made with [Quarto](https://quarto.org/)"

format:
  html:
    theme: 
     - cosmo
     - custom.scss
    lang: en-GB
    toc: false
    anchor-sections: true
    fig-cap-location: margin
    footnotes-hover: true
