---
title: "CV"
---

# Patrick E. Shea

University of Glasgow | School of Social and Political Sciences\
42 Bute Gardens, Glasgow, G12 8RT\
[patrick.shea@glasgow.ac.uk](mailto:patrick.shea@glasgow.ac.uk) | [patrickshea.co.uk](https://patrickshea.co.uk)

## Research and Teaching Interests

Focused on how international finance, sovereign debt, and economic power shape conflict processes, state-building, and domestic politics across countries.

## Academic Positions

**University of Glasgow**, School of Social & Political Sciences

- Senior Lecturer, 2022 – Present
- Subject Lead for [International Political Economy & Development](https://www.gla.ac.uk/research/az/international-political-economy-development/), 2025 – Present
- PhD Convenor, 2023 – 2025

**University of Houston**

- Non-Resident Faculty Fellow, [Center for Public Policy](https://www.uh.edu/hobby/cpp/index.php), 2025 – Present
- Associate Professor, 2019 – 2022
- Assistant Professor, 2013 – 2019

## Education

- Ph.D. Political Science, Rutgers University, 2013. *Advisor*: Jack S. Levy. *Dissertation*: Sovereign Credit, Conflict, and International Relations
- M.A. International Political Economy and Development, Fordham University, 2008
- M.A. Economics, Fordham University, 2008
- B.A. Political Science, Siena College, 2003

## Publications

### Book

Patrick E. Shea (2025) *Hierarchy and the State: State-Building in the Shadow of American Economic Power*. Cambridge University Press.

### Articles

Ulkar Imamverdiyeva, Pablo Pinto, and Patrick E. Shea (2026) "[An Examination of Trade  Liberalization as a Gendered Foreign Policy Instrument](https://www.tandfonline.com/doi/full/10.1080/09692290.2026.2678297)" 
*Review of International Political Economy.*

Lauren Ferry and Patrick E. Shea (2025) "[Crises and Consequences: The Role of U.S. Support in International Bond Markets](https://journals.sagepub.com/doi/10.1177/00220027251327970)" *Journal of Conflict Resolution* 69(10): 1713–1740.

Ben Cormier and Patrick E. Shea (2025) "[Global Finance, Political Business Cycles, and the Politics of Foreign Reserves](https://academic.oup.com/isq/article/69/3/sqaf050/8173439)" *International Studies Quarterly* 69(3).

Matthew DiGiuseppe and Patrick E. Shea (2025) "[Information, Uncertainty, & Public Support for Brinkmanship During the 2023 Debt Limit Negotiation](https://doi.org/10.1017/S0007123424000462)" *British Journal of Political Science* 55(1).

Patrick E. Shea, Bernhard Reinsberg, and Andreas Kern (2025) "[China Lending and the Political Economy of Leader Survival](https://eprints.gla.ac.uk/327639)" *Journal of Conflict Resolution* 69(4): 571–598.

Andreas Kern, Bernhard Reinsberg, and Patrick E. Shea (2024) "[Why Cronies Don't Cry?: IMF Programs, Chinese Lending, and Leader Survival](https://doi.org/10.1007/s11127-023-01114-4)" *Public Choice* 198(3–4), 269–295.

Kathleen J. Brown, Matthew DiGiuseppe, and Patrick E. Shea (2023) "[Ethnic Politics and Sovereign Credit Risk](https://doi.org/10.1080/09692290.2023.2225143)" *Review of International Political Economy* 31(2), 589–621.

Eugenia Artabe, Sam Chapa, Leah Sparkman, and Patrick E. Shea (2023) "[External Threats, Capacity, and Repression: How the Threat of War Affects Political Development and Physical Integrity Rights](https://eprints.gla.ac.uk/299206)" *British Journal of Political Science* 53(4), 1311–1327.

Ulkar Imamverdiyeva and Patrick E. Shea (2022) "[Re-examining Women Leaders and Military Spending](https://eprints.gla.ac.uk/299221)" *Journal of Peace Research* 59(5), 679–693.

Matthew DiGiuseppe and Patrick E. Shea (2022) "[U.S. Patronage, State Capacity, and Civil Conflict](https://doi.org/10.1086/715598)" *Journal of Politics* 84(2): 767–782.

Matthew DiGiuseppe and Patrick E. Shea (2021) "[Alliances, Signals of Support, and Military Effort](https://doi.org/10.1177/13540661211033890)" *European Journal of International Relations* 27(4): 1067–1089.

Jeffrey J. Harden, Justin H. Kirkland, and Patrick E. Shea (2021) "[Legislative Transparency and Credit Risk](https://doi.org/10.1111/lsq.12272)" *Legislative Studies Quarterly* 46(1): 189–218.

Patrick E. Shea and Paul Poast (2020) "[Leaders and Default](https://doi.org/10.1093/isq/sqaa003)" *International Studies Quarterly* 64(2): 406–418.

Patrick E. Shea (2020) "[Money Talks: Finance, War, and Great Power Politics in the 19th Century](https://doi.org/10.1017/ssh.2020.3)" *Social Science History* 44(2): 223–249.

Matthew DiGiuseppe and Patrick E. Shea (2019) "[The Devil's Haircut: Investor-State Disputes Over Debt](https://doi.org/10.1177/0022002718811531)" *Journal of Conflict Resolution* 63(8): 1889–1922.

Markie McBrayer, Patrick E. Shea, and Justin Kirkland (2019) "[The Financial Crisis, Fiscal Federalism, and the Creditworthiness of US State Governments](https://doi.org/10.1515/spp-2018-0003)" *Statistics, Politics and Policy* 9(1): 1–30.

Patrick E. Shea and Paul Poast (2018) "[War and Default](https://doi.org/10.1177/0022002717707239)" *Journal of Conflict Resolution* 62(9): 1876–1904.

Patrick E. Shea and Jonathan Solis (2018) "[Leaders, Tenure, and the Politics of Sovereign Credit](https://doi.org/10.1080/03050629.2018.1406932)" *International Interactions* 44(2), 294–320.

Matthew DiGiuseppe and Patrick E. Shea (2018) "[Sovereign Credit and Political Survival in Democracies](https://doi.org/10.1017/bap.2018.2)" *Business and Politics* 20(3), 360–389. *Finalist for the David P. Baron award for the best article published in BAP in 2018.*

Patrick E. Shea and Charlotte Christian (2017) "[The Impact of Women Legislators on Military Humanitarian Interventions](https://doi.org/10.1177/0022002716631105)" *Journal of Conflict Resolution* 61(10), 2043–2073.

Patrick E. Shea (2016) "[Borrowing Trouble: Sovereign Credit, Military Regimes, and Conflict](https://doi.org/10.1080/03050629.2016.1100611)" *International Interactions* 42(3), 401–428.

Matthew DiGiuseppe and Patrick E. Shea (2016) "[Borrowed Time: Sovereign Finance, Regime Type, and Leader Survival](https://doi.org/10.1111/ecpo.12081)" *Economics & Politics* 28(3), 342–367.

Matthew DiGiuseppe and Patrick E. Shea (2015) "[Sovereign Credit and the Fate of Leaders: Reassessing the Democratic Advantage](https://doi.org/10.1111/isqu.12181)" *International Studies Quarterly* 59(3), 557–570.

Patrick E. Shea (2014) "[Financing Victory: Credit, Democracy, and War](https://doi.org/10.1177/0022002713478567)" *Journal of Conflict Resolution* 58(5), 771–795.

Patrick E. Shea, Terence Teo, and Jack S. Levy (2014) "[Opposition Politics and International Crises: A Formal Model](https://doi.org/10.1111/isqu.12126)" *International Studies Quarterly* 58(4), 741–751.

### Book Chapters

Miriam Shiran and Patrick Shea (forthcoming) "[Survival Analysis in International Relations](https://doi.org/10.4337/9781839101014.00037)" in Joseph Huddleston and Patrick James (eds). *Handbook of Research Methods in International Relations*. Edward Elgar Publishing.

Rosella Cappella Zielinski and Patrick Shea (forthcoming) "[War Finance in the 21st Century](https://doi.org/10.1093/oxfordhb/9780197673546.013.19)" in Vinnie Aggarwal and Tai Ming-Cheung (eds) [*Oxford Handbook of Geoeconomics and Economic Statecraft*](https://academic.oup.com/edited-volume/56064), Oxford University Press.

### Other Writing

"[Donald Trump's peace agreements are also business deals](https://theconversation.com/donald-trumps-peace-agreements-are-also-business-deals-271539)" *The Conversation*, 10 December 2025.

"[US presidents have always used transactional foreign policy – but Trump does it differently](https://theconversation.com/us-presidents-have-always-used-transactional-foreign-policy-but-trump-does-it-differently-262920)" *The Conversation*, 13 August 2025.

"[Why Russia is not taking Trump's threats seriously](https://theconversation.com/why-russia-is-not-taking-trumps-threats-seriously-261296)" *The Conversation*, 16 July 2025.

"[War Finance in the 21st Century: Insights from Ukraine, Syria, and Beyond](https://ucigcc.org/blog/war-finance-in-the-21st-century-insights-from-ukraine-syria-and-beyond/)" with Rosella Capella Zielinski, March 2025, Institute on Global Conflict and Cooperation.

"[Why a US minerals deal with Ukraine won't deter Russian aggression](https://theconversation.com/why-a-us-minerals-deal-with-ukraine-wont-deter-russian-aggression-251436)" *The Conversation*, 7 March 2025.

"[What happens next in Ukraine's debt negotiations could change the course of the war](https://theconversation.com/what-happens-next-in-ukraines-debt-negotiations-could-change-the-course-of-the-war-233355)" *The Conversation*, 1 July 2024.

"[The whole world is facing a debt crisis – but richer countries can afford to stop it](https://theconversation.com/the-whole-world-is-facing-a-debt-crisis-but-richer-countries-can-afford-to-stop-it-192119)" *The Conversation*, 26 October 2022.

## External Funding

*International Coercion, Debt Relief, and Land Transactions*, Principal Investigator, 2021–2023. National Science Foundation, Security & Preparedness #2048406 (Co-PI, Jonas Bunte, Vienna University), $363,736.

*World Politics & Statecraft Fellowship*, Smith Richardson Foundation, 2012, $12,000.

## Selected Works In Progress

"Predicting Debt Crisis" with Matt DiGiuseppe

"Politics of Odious Debt" with Matt DiGiuseppe

"Politics of Financial Disclosure and Firms" with Justin Kirkland

"Green Land Deals" with Maha Rafi Atal

"Political Economy of International Land Acquisitions" with Jonas Bunte and Burak Giray

## Awards and Small Grants

- 2019, 2021: Provost Travel Award
- 2019: Finalist for the Ross Lence teaching award, University of Houston
- 2018: Finalist for the David P. Baron award in *Business & Politics*
- 2016: Small Research Grant, University of Houston
- 2015: New Faculty Grant, University of Houston
- 2015: Research Progress Grant, University of Houston
- 2013: Kenneth Boulding Award, Best Graduate Student Paper, Peace Studies Section in ISA
- 2012: Triangle Institute for Security Studies New Faces
- 2012: Rutgers Special Study Opportunity Award
- 2011: Rutgers Pre-Dissertation Research Grant
- 2009: Rutgers Special Study Opportunity Award

## Presentations

### Invited Talks

Boston University's Project on Political Economy of Security, Essex University, Lehigh University, Rice University, Leiden University, Durham University

### Conferences and Workshops

Development Finance Conference, Boston University 2025 | European Political Science Association: 2023–2025 | European Political Science Society: 2026 | Green Capitalism workshop (co-organizer), University of Glasgow 2025 | Political Economy of Aid and Development Society (co-organizer) 2025 | Global Governance in an Age of Disorder 2025 | Global Policy North 2023, 2025 | British International Studies Association: 2023 | American Political Science Association: 2010–2019 | International Studies Association: 2010, 2012, 2013, 2015–2018, 2021, 2022 | Midwest International Studies Association: 2020 | Midwest Political Science Association: 2009, 2011, 2014 | Peace Science Society: 2010, 2012, 2015 | International Political Economy Society: 2017, 2021 | Southern Political Science Association: 2018, 2022 | Pitt-Princeton Political Economy of Government Revenues Conference 2015 | Texas Triangle International Relations Conference: 2014–2020, 2022 | Triangle Institute for Security Studies New Faces: 2012

## Teaching

### University of Glasgow

Data for Development (graduate) | Political Economy of Conflict (graduate) | International Political Economy (honours)

### University of Houston

International Relations Seminar (graduate) | Research Methods (graduate) | Empirical Challenges in International Relations Research (graduate) | Introduction to International Relations | Causes and Politics of War

### Methods Training Programmes

Linear Regression, Odum Institute, University of North Carolina, 2024–2025\
Linear Regression, ICPSR Summer Program, 2019–2021, 2023–2026\
Generalized Linear Models, Essex Summer School in Social Science Data Analysis, 2017–2019

### Mentorship

**University of Glasgow**: PhD Convenor (2023–Present) | Staff Mentor | Workshop for Presentations | Undergraduate Thesis Advisor | Graduate Thesis Advisor

**University of Houston**: Peace Corps Prep 2020 | Workshop for Applying to Graduate School 2016–2018 | Graduate School Poster Session Training 2019 | Graduate Student Poster Session Organizer 2015, 2017, 2019, 2021 | Summer Undergraduate Research Fellowship Mentor 2014, 2017 | Provost Undergraduate Research Fellowship Mentor 2014 | Undergraduate Research Weekend 2017

### Dissertation and Thesis Advising

Dissertation Committee Member for Rhulani Ramela (Expected 2028) | Dissertation Committee Member for Julián Velázquez (Expected 2028) | Dissertation Committee Member for Matthew Heneghan (Expected 2028) | Dissertation Committee Member for Louise Wilson (Expected 2029) | Dissertation Committee Member for Zhihang Wu (Expected 2026) | Dissertation Committee Member for Tom Hanna (Expected 2025) | Dissertation Committee Member for Rita Naoum (2024) | Dissertation Committee Member for Myriam Shiran (2023) | Dissertation Committee Member for Samad Karimov (2022) | Dissertation Committee Member for Burak Giray (2022) | Dissertation Committee Chair for Ulkar Imamverdi (2021) | Dissertation Committee Member for Haeyong Lim (2019) | Dissertation Committee Member for Leonardo Antenangeli (2018) | Dissertation Committee Member for Paula Pineda (2016) | Master's Thesis Committee Chair for Charlotte Christian (2018) | Master's Thesis Committee Member for Joseph Lazzarro (2016) | Honor's Thesis Committee Member for Josh Jackson (2014)

## Service

### Department and University Service

Subject Lead, International Political Economy (2025 – Present) | PhD Convener, University of Glasgow (2023–2025) | Political Economy of Development Society Committee (2025) | Faculty Governance and Advisory Committee (FGAC) 2020–2021 | International Relations Field Chair 2019–2021 | Speaker Series Coordinator, University of Houston 2016–2017 | International Relations Search Committee Member 2013, 2015, 2017 | Comparative Politics Search Committee Member 2020 | Political Economy of Cooperation and Conflict Conference Organizer, 2017 | Political Economy of Risk Conference Organizer, 2016 | IR/Comparative Research Workshop, University of Houston 2014–2016 | Technology Committee, University of Houston 2015, 2017 | Instructional Assistant Professor Search, University of Houston 2015 | Undergraduate Committee Member, University of Houston 2014 | Outreach Committee Member, University of Houston 2014, 2019 | Graduate Committee Member, University of Houston 2013, 2016, 2018

### Other Academic Service

ESRC Assessor College (2025 – Present) | British Council International Science Partnerships Fund College of Reviewers | External Examiner, Politics and IR, Royal Holloway (2025–Present) | Associate Editor, *Politics* (journal) | Committee member for Grawemeyer Award for Ideas Improving World Order 2019 | Organizer of Texas Triangle International Relations Conference 2019–2020

### Referee

*American Journal of Political Science*, *American Political Science Review*, *American Politics Research*, *Applied Economic Letters*, *British Council*, *Business & Politics*, *Comparative Political Studies*, *Conflict Management and Peace Science*, *Defence and Peace Economics*,  *Democratization*, *Economics & Politics*, *Feminist Economics*, *Foreign Policy Analysis*, *International Interactions*, *International Organization*, *International Political Science Review*, *International Security*, *International Studies Quarterly*, *International Studies Review*, *Journal of Conflict Resolution*, *Journal of International Relations and Development*, *Journal of Global Security Studies*, *Journal of Peace Research*, *Journal of Politics*, *Oxford University Press*, *Political Research Quarterly*, *Political Studies*, *Review of International Organizations*, *Review of International Political Economy*, *Regulation & Governance*, *Socio-Economic Review*, *Social Science Journal*, *UK Research and Innovation (UKRI)*, *World Politics*

## Related Experience

- United States Peace Corps Volunteer, Haiti, 2003–2005
- Robert F. Kennedy Memorial Center for Human Rights, Intern, 2005
- Futures Group (International Development NGO), Assistant, 2005–2006
- U.S. State Department, Intern, 2007
